### ISSUE TITLE
Deprecations in deps/build.jl

### ISSUE THREAD

**Issue by sbromberger** [JuliaWeb/GnuTLS.jl#30]
I tried fixing them via https://gist.github.com/sbromberger/ece0c7b7b59859bdf0d3 but I'm still getting errors in 0.3:

```
INFO: Building Nettle
INFO: Building GnuTLS
===============================[ ERROR: GnuTLS ]================================

@compat not defined
while loading /Users/seth/.julia/v0.3/GnuTLS/deps/build.jl, in expression starting on line 76
```

I don't know why the code within that `if` block is being evaluated.

**Comment by catawbasam** [comment]
@sbromberger do you still see this?   I just ran Pkg.build("GnuTLS") and it seemed to run ok.

**Comment by sbromberger** [comment]
@catawbasam it happens when I tried fixing the deprecations with that gist I pasted. Can you confirm that the gist no longer errors out (around line 70)?

**Comment by catawbasam** [comment]
I do get an error from that code.  However, it looks to me like--
```
if Base.VERSION >= v"0.4.0-dev"
	@BinDeps.install @compat Dict(:gnutls => :gnutls)
else
	@BinDeps.install [:gnutls => :gnutls]
end
```
could be shortened to simply `@BinDeps.install` since we don't appear to be aliasing the library name.
That eliminates the error.

Also,
```
julia_usrdir = normpath(JULIA_HOME*"/../") # This is a stopgap, we need a better builtin solution to get the included libraries
libdirs = String["$(julia_usrdir)/lib"]
includedirs = String["$(julia_usrdir)/include"]
```
yields `//lib` in the paths.  
I think it should be `julia_usrdir = normpath(JULIA_HOME*"/..")`.

**Comment by quinnj** [comment]
Is this still an issue?

**Comment by wildart** [comment]
No
