### ISSUE TITLE
require GnuTLS >= 2.9.10?

### ISSUE THREAD

**Issue by stevengj** [JuliaWeb/GnuTLS.jl#4]
As discussed [https://groups.google.com/forum/?fromgroups=#!topic/julia-users/pwCg0_KjJ7Y on the mailing list], there seem to be some problems with HMAC signatures with old GnuTLS versions.  According to their [http://gitorious.org/gnutls/gnutls/blobs/master/NEWS NEWS file], the `gnutls_hmac_*` functions were apparently only added in 2.9.10.

**Comment by sbromberger** [comment]
I've implemented warnings for outdated GnuTLS versions in #36. Basically, we need to keep up with security alerts and set `GNUTLS_MINSECURE_VER` in GnuTLS.jl for each supported major/minor pair.
