### ISSUE TITLE
Inconsistent behavior of hexdigest! (and gnutls_hmac_output) between GnuTLS versions

### ISSUE THREAD

**Issue by simonster** [JuliaWeb/GnuTLS.jl#5]
The following test passes in 3.1.10 but fails in 2.12.5:

```julia
h = HMACState(SHA256,"key")
update(h,"The quick brown fox jumps over the lazy dog")
@test hexdigest!(h) == "f7bc83f430538424b13298e6aa6fb143ef4d59a14946175997479dbc2d1a3cd8"
update(h,"The quick brown fox jumps over the lazy dog")
@test hexdigest!(h) == "f7bc83f430538424b13298e6aa6fb143ef4d59a14946175997479dbc2d1a3cd8"
```

In 2.12.5, I get `6b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920` the second time around. I'm not actually sure where this comes from, since 

```julia
h = HMACState(SHA256,"key")
update(h,"The quick brown fox jumps over the lazy dog")
update(h,"The quick brown fox jumps over the lazy dog")
hexdigest!(h)
```

yields `563d87fd06455e5809679f6153df494301b543b9720113876ac44e0c9fd55299`.

This seems like it could be fixed by reinitializing the HMAC after `hexdigest!` for old versions of GnuTLS, although I'm not sure when this was fixed/changed.

**Comment by sbromberger** [comment]
Tidying up and closing this out, since it appears to reference a problem in versions of GnuTLS that are deprecated.
