### ISSUE TITLE
GnuTLS.jl not building on Debian

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/GnuTLS.jl#52]
Hi there,
I am having trouble building GnuTLS.jl on Debian Jessie.
When I enter ```Pkg.build("GnuTLS")``` I get the following error:

```File String["/root/.julia/v0.3/GnuTLS/deps/src/nettle-2.7"] was not created successfully (Tried to run SynchronousStepCollection({`tar xzf /root/.julia/v0.3/GnuTLS/deps/downloads/nettle-2.7.tar.gz --directory=/root/.julia/v0.3/GnuTLS/deps/src`},"","") )
while loading /root/.julia/v0.3/GnuTLS/deps/build.jl, in expression starting on line 55```

But ```/root/.julia/v0.3/GnuTLS/deps/src/nettle-2.7``` does exist and is full of source files as expected.
Also, Nettle.jl is installed and works fine.

Any ideas?

Thanks,
Jock

**Comment by JockLawrie** [comment]
After a little digging around I found a workaround, namely reinstall *libnettle* and *libgnutls*.
That GnuTLS.jl doesn't sort this out automatically remains an issue, but at least one can get it working. Here are the steps I used:

Shell:
```apt-get --reinstall install libnettle4```
```apt-get --reinstall install reinstall libgnutls-deb0-28```

Julia:
```julia
Pkg.rm("GnuTLS")
```

Shell:
```cd ~/.julia/v0.3```
```ls -ail```

If directory GnuTLS exists, delete it:
```rm -rf GnuTLS```

Julia:
```julia
Pkg.update()
```

If GnuTLS is not installed (probably because none of your other packages require it), then install it:
```julia
Pkg.add("GnuTLS")
```

**Comment by JockLawrie** [comment]
p.s., you may also need to install *libgmp-dev* as a first step, before (re)installing libnettle:
```apt-get install libgmp-dev```

**Comment by quinnj** [comment]
Thanks for tracking this down @JockLawrie; we'll point people here in for future reference.
