### ISSUE TITLE
GnuTLS (nettle) doesn't build on RHEL6.1

### ISSUE THREAD

**Issue by GlenHertz** [JuliaWeb/GnuTLS.jl#6]
Hi,

I tried installing GnuTLS on RHEL6.1 (64-bit) and it failed during the compile of nettle.  After some debugging I determined I needed a newer version of openssl (I used the latest, 1.0.1e), I did:

`cd ~/downloads/openssl-1.0.1e
./config --prefix=$HOME/apps/openssl-1.0.1e && make && make install`

Then to compile nettle I did:
```export LD_LIBRARY_PATH=$HOME/apps/openssl-1.0.1e/lib
export LDFLAGS=-L$HOME/apps/openssl-1.0.1e/lib
cd ~/.julia/GnuTLS/deps/src/nettle-2.7
./configure --prefix=/u/hertz/.julia/GnuTLS/deps/usr
make && make install```

But then I'm not sure how to continue on with the build of GnuTLS.  Any pointers?  I would like to try to get all the way through the install (I'm wanting to test IJulia).

Would it be possible to compile openssl before nettle so that this will install smoothly on more systems? 

Thanks,

Glen

**Comment by sbromberger** [comment]
Closing out since I think this is no longer an issue - if not, please let me know and I'll reopen.
