### ISSUE TITLE
Nettle.jl API breakage

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/GnuTLS.jl#60]
[Nettle](https://github.com/staticfloat/Nettle.jl) has just broken its API significantly, in order to be much more precompile-friendly.  The big takeaway is that methods such as `md5_hash(data)` should be mapped to `digest("md5", data)`, there are no more auto-generated types for hashes, and internally the code is a little easier to grok.  This new version of `Nettle.jl` has not been released yet, I will make every effort to ensure that dependent packages such as this one have a chance to adapt before releasing the new version.

**Comment by staticfloat** [comment]
I just went through here and realized this package doesn't actually use the `Nettle` julia code at all.

**Comment by tkelman** [comment]
Why's it in REQUIRE then?

**Comment by staticfloat** [comment]
They are essentially using `Nettle.jl` as a glorified bindeps script; then they use `ccall` exclusively.

**Comment by Keno** [comment]
Correct

**Comment by tkelman** [comment]
whoops missed that it's in the deps.jl script. carry on
